[[questions]]
type = "MultipleChoice"
prompt.prompt = """
```ocaml
type user = {
  id : Uuid.t;
  mutable last_active : float
}
```

Provided the above definition of the `user` type, select all of the programs that type check, or "None of the above."
"""
prompt.distractors = ["""
  ```ocaml
  let foo (users : user array @ contended) =
    users.(0)
  ```
  """, """
  ```ocaml
  let foo (users : user array @ contended) =
    users.(0).last_active
  ```
  """, """
  ```ocaml
  let foo (users : user array @ contended) =
    users.(0).id
  ```
  """, """
  ```ocaml
  let foo (users : user array @ contended) =
    users.(0) <- { id = id ; last_active = Unix.time () }
  ```
  """, """
  ```ocaml
  let foo (users : user array @ contended) =
    users.(0).last_active <- Unix.time ()
  ```
  """]
prompt.answerIndex = 5
answer.answer = ["None of the above"]
context = """
Array elements are mutable places, thus elements of a contended array cannot be *read or written*
"""
id = "2df5cc1b-82c6-47d0-82ea-b7bc237b9d85"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
```ocaml
let make_box s = exclave_
  ref s

let () = 
  let ls = [ ref 0 ] in
  let ls @ local = stack_ (make_box 1 :: ls)  in
  (* here *)
  ...
```

Select which diagram best represents the memory while executing the line marked `(* here *)`
"""
prompt.distractors = [
  "![Maybe answer](assets/q2-memory-b.svg)",
  "![Maybe answer](assets/q2-memory-c.svg)",
  "![Maybe answer](assets/q2-memory-d.svg)",
]
answer.answer = "![Maybe answer](assets/q2-memory-a.svg)"
context = """
The expression `[ ref 0 ]` is not stack allocated.
"""
id = "619274ba-08ad-4236-8874-d0023ebc631e"

[multipart]
q = """
```ocaml
type user = {
  id : Uuid.t;
  mutable last_active : float
}

let f1 : user -> int
    = (* ... *)

let f2 : (user @ contended) -> int
    = (* ... *)

let f3 : (user -> int) @ portable
    = (* ... *)
```

You will be given a series of statements about the possible implementations of the functions `f1`, `f2`, and `f3`. For each statement select whether it is "true" or "false" based on the rules of contention and portability.
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f1` could modify its parameter"
prompt.distractors = ["False"]
prompt.answerIndex = 0
answer.answer = "True"
context = """
The parameter is uncontended and no restrictions exist for uncontended references
"""
id = "583663ba-347b-406d-89ba-a6d47d582b91"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f1` could not be portable because its parameter is uncontended"
prompt.distractors = ["True"]
prompt.answerIndex = 1
answer.answer = "False"
context = """
There are no restrictions on the type of references a portable function accepts as parameters
"""
id = "9e1ce845-82c2-4dbe-8ace-0933ecedf4e7"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f2` can update the `last_active` field of its parameter"
prompt.distractors = ["True"]
prompt.answerIndex = 1
answer.answer = "False"
context = """
Mutable fields of contended values cannot be read or written
"""
id = "3cb44168-a78b-4f40-92d6-942eebae7a10"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f2` can write to references it captures"
prompt.distractors = ["False"]
prompt.answerIndex = 0
answer.answer = "True"
context = """
Nonportable functions can capture references as uncontended
"""
id = "56fb30d9-175a-4884-bf23-146c459db16a"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f2` can read the `id` field of its parameter"
prompt.distractors = ["False"]
prompt.answerIndex = 0
answer.answer = "True"
context = """
Deeply immutable values mode cross along the contention axis.
"""
id = "a9c3b558-bcb0-4e99-99d7-027c4ef2ecd3"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f3` can read from mutable fields of captured references"
prompt.distractors = ["True"]
prompt.answerIndex = 1
answer.answer = "False"
context = """
References captured by portable functions are contended
"""
id = "06769b4a-b030-4022-a948-2ef56993614e"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f3` can only capture references as contended"
prompt.distractors = ["False"]
prompt.answerIndex = 0
answer.answer = "True"
context = """
References captured by portable functions are contended
"""
id = "5a5c134c-a831-421c-ad9d-3a2a4a20dd29"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = "The implementation of `f3` can update the `last_active` field of its parameter"
prompt.distractors = ["False"]
prompt.answerIndex = 0
answer.answer = "True"
context = """
Uncontended values may be read and written to
"""
id = "e7e22a6b-7ffa-45d4-b5ac-35112e1630a7"
